config/routes.rb
Rails.application.routes.draw do
  resources :flights

  
  root 'pages#home'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'UNT#19, Thank you!' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:one, :two, :three, :four, :five)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :one %><br>
    <%= f.text_area :one %>
  </div>
  <div class="field">
    <%= f.label :two %><br>
    <%= f.text_area :two %>
  </div>
  <div class="field">
    <%= f.label :three %><br>
    <%= f.text_area :three %>
  </div>
  <div class="field">
    <%= f.label :four %><br>
    <%= f.text_area :four %>
  </div>
  <div class="field">
    <%= f.label :five %><br>
    <%= f.text_area :five %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Fave Social Site?</th>
      <th>Tweet or Insta?</th>
      <th>You Pin?</th>
      <th>On Mobile?</th>
      <th>Any Comment?</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight %></td>
        <td><%= flight.one %></td>
        <td><%= flight.two %></td>
        <td><%= flight.three %></td>
        <td><%= flight.four %></td>
        <td><%= flight.five %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p>
  <strong>One:</strong>
  <%= @flight.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @flight.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @flight.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @flight.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @flight.five %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>First Flight Survey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, initial-scale=1"> 
		<title>First Flight Survey</title>
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->

			<header class="codrops-header">
				<h1>Thank you for taking this survey. <span>5 Questions for First Flight Freshman</span></h1>	
			</header>
			<section>
				<form accept-charset="UTF-8" action="../flights" method="post" id="theForm" class="simform">
          <input name="utf8" type="hidden" value="&#x2713;" />
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
					<div class="simform-inner">
						<ol class="questions">
							<li>
								<span><label for="flight_one">So what social media site do you prefer to use?</label></span>
								<input id="q1" name="flight[one]" type="text"/>
							</li>
							<li>
								<span><label for="q2">Would you rather use Instagram, Twitter, both, or neither?</label></span>
								<input id="q2" name="flight[two]" type="text"/>
							</li>
							<li>
								<span><label for="q3">Do you use Pinterest?</label></span>
								<input id="q3" name="flight[three]" type="text"/>
							</li>
							<li>
								<span><label for="q4">Are you taking this survey on a mobile device?</label></span>
								<input id="q4" name="flight[four]" type="text"/>
							</li>
							<li>
								<span><label for="q5">Would you like to leave a brief comment about the First Flight website?</label></span>
								<input id="q5" name="flight[five]" type="text"/>
							</li>
						</ol><!-- /questions -->
						<button class="submit" name="commit" type="submit" value="Create Flight">Send answers</button>
						<div class="controls">
							<button class="next"></button>
							<div class="progress"></div>
							<span class="number">
								<span class="number-current"></span>
								<span class="number-total"></span>
							</span>
							<span class="error-message"></span>
						</div><!-- / controls -->
					</div><!-- /simform-inner -->
					<span class="final-message"></span>
				</form><!-- /simform -->			
			</section>

		</div><!-- /container -->
		<script src="js/classie.js"></script>
		<script src="js/stepsForm.js"></script>
		<script>
			var theForm = document.getElementById( 'theForm' );
                        //disable form autocomplete
                        theForm.setAttribute( "autocomplete", "off" );

			new stepsForm( theForm, {
				onSubmit : function( form ) {
					// hide form
					classie.addClass( theForm.querySelector( '.simform-inner' ), 'hide' );
					
          form.submit()

          /*
					or
					AJAX request (maybe show loading indicator while we don't have an answer..)
					*/

					// let's just simulate something...
					var messageEl = theForm.querySelector( '.final-message' );
					messageEl.innerHTML = 'UNT #19, good luck with your first year on campus.';
					classie.addClass( messageEl, 'show' );
				}
			} );
		</script>
	</body>